// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/kv.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_api_proto_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_api_proto_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{1}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_proto_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type DelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRequest) Reset() {
	*x = DelRequest{}
	mi := &file_api_proto_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequest) ProtoMessage() {}

func (x *DelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequest.ProtoReflect.Descriptor instead.
func (*DelRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{4}
}

func (x *DelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelResponse) Reset() {
	*x = DelResponse{}
	mi := &file_api_proto_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResponse) ProtoMessage() {}

func (x *DelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResponse.ProtoReflect.Descriptor instead.
func (*DelResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{5}
}

func (x *DelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// InternalSet 节点间数据迁移专用写入（绕过 Raft，直接写入 engine）
type InternalSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalSetRequest) Reset() {
	*x = InternalSetRequest{}
	mi := &file_api_proto_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalSetRequest) ProtoMessage() {}

func (x *InternalSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalSetRequest.ProtoReflect.Descriptor instead.
func (*InternalSetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{6}
}

func (x *InternalSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *InternalSetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type InternalSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalSetResponse) Reset() {
	*x = InternalSetResponse{}
	mi := &file_api_proto_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalSetResponse) ProtoMessage() {}

func (x *InternalSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalSetResponse.ProtoReflect.Descriptor instead.
func (*InternalSetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{7}
}

func (x *InternalSetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Status 查询节点状态
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_proto_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{8}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // "cp" | "ap"
	EngineType    string                 `protobuf:"bytes,3,opt,name=engine_type,json=engineType,proto3" json:"engine_type,omitempty"`
	Stats         *EngineStatsMsg        `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	Healthy       bool                   `protobuf:"varint,5,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_proto_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{9}
}

func (x *StatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StatusResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StatusResponse) GetEngineType() string {
	if x != nil {
		return x.EngineType
	}
	return ""
}

func (x *StatusResponse) GetStats() *EngineStatsMsg {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *StatusResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type EngineStatsMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EngineType    string                 `protobuf:"bytes,1,opt,name=engine_type,json=engineType,proto3" json:"engine_type,omitempty"`
	EntryCount    int64                  `protobuf:"varint,2,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineStatsMsg) Reset() {
	*x = EngineStatsMsg{}
	mi := &file_api_proto_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineStatsMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineStatsMsg) ProtoMessage() {}

func (x *EngineStatsMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineStatsMsg.ProtoReflect.Descriptor instead.
func (*EngineStatsMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{10}
}

func (x *EngineStatsMsg) GetEngineType() string {
	if x != nil {
		return x.EngineType
	}
	return ""
}

func (x *EngineStatsMsg) GetEntryCount() int64 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *EngineStatsMsg) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

// RaftInfo 查询 Raft 状态（仅 CP 模式有效）
type RaftInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftInfoRequest) Reset() {
	*x = RaftInfoRequest{}
	mi := &file_api_proto_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftInfoRequest) ProtoMessage() {}

func (x *RaftInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftInfoRequest.ProtoReflect.Descriptor instead.
func (*RaftInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{11}
}

type RaftInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	CommitIndex   uint64                 `protobuf:"varint,3,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	LastApplied   uint64                 `protobuf:"varint,4,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	HealthyNodes  int32                  `protobuf:"varint,5,opt,name=healthy_nodes,json=healthyNodes,proto3" json:"healthy_nodes,omitempty"`
	Peers         []string               `protobuf:"bytes,6,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftInfoResponse) Reset() {
	*x = RaftInfoResponse{}
	mi := &file_api_proto_kv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftInfoResponse) ProtoMessage() {}

func (x *RaftInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftInfoResponse.ProtoReflect.Descriptor instead.
func (*RaftInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kv_proto_rawDescGZIP(), []int{12}
}

func (x *RaftInfoResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RaftInfoResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftInfoResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *RaftInfoResponse) GetLastApplied() uint64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

func (x *RaftInfoResponse) GetHealthyNodes() int32 {
	if x != nil {
		return x.HealthyNodes
	}
	return 0
}

func (x *RaftInfoResponse) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

var File_api_proto_kv_proto protoreflect.FileDescriptor

const file_api_proto_kv_proto_rawDesc = "" +
	"\n" +
	"\x12api/proto/kv.proto\x12\aservice\"4\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"'\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x1e\n" +
	"\n" +
	"DelRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"'\n" +
	"\vDelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"<\n" +
	"\x12InternalSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"/\n" +
	"\x13InternalSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x0f\n" +
	"\rStatusRequest\"\xa7\x01\n" +
	"\x0eStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1f\n" +
	"\vengine_type\x18\x03 \x01(\tR\n" +
	"engineType\x12-\n" +
	"\x05stats\x18\x04 \x01(\v2\x17.service.EngineStatsMsgR\x05stats\x12\x18\n" +
	"\ahealthy\x18\x05 \x01(\bR\ahealthy\"u\n" +
	"\x0eEngineStatsMsg\x12\x1f\n" +
	"\vengine_type\x18\x01 \x01(\tR\n" +
	"engineType\x12\x1f\n" +
	"\ventry_count\x18\x02 \x01(\x03R\n" +
	"entryCount\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x03R\vmemoryBytes\"\x11\n" +
	"\x0fRaftInfoRequest\"\xbb\x01\n" +
	"\x10RaftInfoResponse\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12!\n" +
	"\fcommit_index\x18\x03 \x01(\x04R\vcommitIndex\x12!\n" +
	"\flast_applied\x18\x04 \x01(\x04R\vlastApplied\x12#\n" +
	"\rhealthy_nodes\x18\x05 \x01(\x05R\fhealthyNodes\x12\x14\n" +
	"\x05peers\x18\x06 \x03(\tR\x05peers2\xe7\x02\n" +
	"\tKVService\x120\n" +
	"\x03Set\x12\x13.service.SetRequest\x1a\x14.service.SetResponse\x120\n" +
	"\x03Get\x12\x13.service.GetRequest\x1a\x14.service.GetResponse\x120\n" +
	"\x03Del\x12\x13.service.DelRequest\x1a\x14.service.DelResponse\x12H\n" +
	"\vInternalSet\x12\x1b.service.InternalSetRequest\x1a\x1c.service.InternalSetResponse\x129\n" +
	"\x06Status\x12\x16.service.StatusRequest\x1a\x17.service.StatusResponse\x12?\n" +
	"\bRaftInfo\x12\x18.service.RaftInfoRequest\x1a\x19.service.RaftInfoResponseB\x1bZ\x19Flux-KV/api/proto;serviceb\x06proto3"

var (
	file_api_proto_kv_proto_rawDescOnce sync.Once
	file_api_proto_kv_proto_rawDescData []byte
)

func file_api_proto_kv_proto_rawDescGZIP() []byte {
	file_api_proto_kv_proto_rawDescOnce.Do(func() {
		file_api_proto_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_kv_proto_rawDesc), len(file_api_proto_kv_proto_rawDesc)))
	})
	return file_api_proto_kv_proto_rawDescData
}

var file_api_proto_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_kv_proto_goTypes = []any{
	(*SetRequest)(nil),          // 0: service.SetRequest
	(*SetResponse)(nil),         // 1: service.SetResponse
	(*GetRequest)(nil),          // 2: service.GetRequest
	(*GetResponse)(nil),         // 3: service.GetResponse
	(*DelRequest)(nil),          // 4: service.DelRequest
	(*DelResponse)(nil),         // 5: service.DelResponse
	(*InternalSetRequest)(nil),  // 6: service.InternalSetRequest
	(*InternalSetResponse)(nil), // 7: service.InternalSetResponse
	(*StatusRequest)(nil),       // 8: service.StatusRequest
	(*StatusResponse)(nil),      // 9: service.StatusResponse
	(*EngineStatsMsg)(nil),      // 10: service.EngineStatsMsg
	(*RaftInfoRequest)(nil),     // 11: service.RaftInfoRequest
	(*RaftInfoResponse)(nil),    // 12: service.RaftInfoResponse
}
var file_api_proto_kv_proto_depIdxs = []int32{
	10, // 0: service.StatusResponse.stats:type_name -> service.EngineStatsMsg
	0,  // 1: service.KVService.Set:input_type -> service.SetRequest
	2,  // 2: service.KVService.Get:input_type -> service.GetRequest
	4,  // 3: service.KVService.Del:input_type -> service.DelRequest
	6,  // 4: service.KVService.InternalSet:input_type -> service.InternalSetRequest
	8,  // 5: service.KVService.Status:input_type -> service.StatusRequest
	11, // 6: service.KVService.RaftInfo:input_type -> service.RaftInfoRequest
	1,  // 7: service.KVService.Set:output_type -> service.SetResponse
	3,  // 8: service.KVService.Get:output_type -> service.GetResponse
	5,  // 9: service.KVService.Del:output_type -> service.DelResponse
	7,  // 10: service.KVService.InternalSet:output_type -> service.InternalSetResponse
	9,  // 11: service.KVService.Status:output_type -> service.StatusResponse
	12, // 12: service.KVService.RaftInfo:output_type -> service.RaftInfoResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_kv_proto_init() }
func file_api_proto_kv_proto_init() {
	if File_api_proto_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_kv_proto_rawDesc), len(file_api_proto_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_kv_proto_goTypes,
		DependencyIndexes: file_api_proto_kv_proto_depIdxs,
		MessageInfos:      file_api_proto_kv_proto_msgTypes,
	}.Build()
	File_api_proto_kv_proto = out.File
	file_api_proto_kv_proto_goTypes = nil
	file_api_proto_kv_proto_depIdxs = nil
}
